export const SET_INITIAL_PROMPT_REQUEST = "SET_INITIAL_PROMPT_REQUEST";
export const SET_INITIAL_PROMPT_FAILURE = "SET_INITIAL_PROMPT_FAILURE";
export const SET_INITIAL_PROMPT_SUCCESS = "SET_INITIAL_PROMPT_SUCCESS";

export const ADD_INTERRACTION_REQUEST = "ADD_INTERRACTION_REQUEST";
export const ADD_INTERRACTION_FAILURE = "ADD_INTERRACTION_FAILURE";
export const ADD_INTERRACTION_SUCCESS = "ADD_INTERRACTION_SUCCESS";